import type { University } from '@/types';

const universities: Record<string, University> = {
  // ── Belgium ──────────────────────────────────────────────
  ulb: {
    id: 'ulb',
    name: 'Université Libre de Bruxelles',
    shortName: 'ULB',
    searchQuery: 'ulb',
    emailDomain: 'ulb.be',
    country: 'BE',
    city: 'Bruxelles',
    colors: {
      primary: '#1e3a5f',
      gradient: 'linear-gradient(135deg, #1e3a5f 0%, #2d5a8e 100%)',
      chipBg: '#1e3a5f',
      chipText: '#ffffff',
      selectedDate: '#1e3a5f',
      hoverDate: '#15293f',
    },
    libraryOverrides: {
      'ulb-bss': { forceBookingAvailable: true },
      'ulb-bonn-hb': { forceBookingAvailable: false },
    },
  },
  uclouvain: {
    id: 'uclouvain',
    name: 'UCLouvain',
    shortName: 'UCLouvain',
    searchQuery: 'UCLouvain',
    emailDomain: 'uclouvain.be',
    country: 'BE',
    city: 'Louvain-la-Neuve',
    colors: {
      primary: '#003366',
      gradient: 'linear-gradient(135deg, #003366 0%, #004d99 100%)',
      chipBg: '#003366',
      chipText: '#ffffff',
      selectedDate: '#003366',
      hoverDate: '#002244',
    },
    libraryOverrides: {},
  },
  unamur: {
    id: 'unamur',
    name: 'Université de Namur',
    shortName: 'UNamur',
    searchQuery: 'UNamur',
    emailDomain: 'unamur.be',
    country: 'BE',
    city: 'Namur',
    colors: {
      primary: '#1a3c6e',
      gradient: 'linear-gradient(135deg, #1a3c6e 0%, #2a5ca8 100%)',
      chipBg: '#1a3c6e',
      chipText: '#ffffff',
      selectedDate: '#1a3c6e',
      hoverDate: '#122a4d',
    },
    libraryOverrides: {},
  },
  vub: {
    id: 'vub',
    name: 'Vrije Universiteit Brussel',
    shortName: 'VUB',
    searchQuery: 'VUB',
    emailDomain: 'vub.be',
    country: 'BE',
    city: 'Bruxelles',
    colors: {
      primary: '#003058',
      gradient: 'linear-gradient(135deg, #003058 0%, #004a8a 100%)',
      chipBg: '#003058',
      chipText: '#ffffff',
      selectedDate: '#003058',
      hoverDate: '#002040',
    },
    libraryOverrides: {},
  },
  ugent: {
    id: 'ugent',
    name: 'Universiteit Gent',
    shortName: 'UGent',
    searchQuery: 'Ghent University',
    emailDomain: 'ugent.be',
    country: 'BE',
    city: 'Gent',
    colors: {
      primary: '#1e6b52',
      gradient: 'linear-gradient(135deg, #1e6b52 0%, #2a9d78 100%)',
      chipBg: '#1e6b52',
      chipText: '#ffffff',
      selectedDate: '#1e6b52',
      hoverDate: '#15503e',
    },
    libraryOverrides: {},
  },

  // ── Switzerland ──────────────────────────────────────────
  unil: {
    id: 'unil',
    name: 'Université de Lausanne',
    shortName: 'UNIL',
    searchQuery: 'UNIL',
    emailDomain: 'unil.ch',
    country: 'CH',
    city: 'Lausanne',
    colors: {
      primary: '#e63312',
      gradient: 'linear-gradient(135deg, #e63312 0%, #ff5533 100%)',
      chipBg: '#e63312',
      chipText: '#ffffff',
      selectedDate: '#e63312',
      hoverDate: '#b8280e',
    },
    libraryOverrides: {},
  },
  unige: {
    id: 'unige',
    name: 'Université de Genève',
    shortName: 'UNIGE',
    searchQuery: 'UNIGE',
    emailDomain: 'unige.ch',
    country: 'CH',
    city: 'Genève',
    colors: {
      primary: '#7b2d8e',
      gradient: 'linear-gradient(135deg, #7b2d8e 0%, #9b4db0 100%)',
      chipBg: '#7b2d8e',
      chipText: '#ffffff',
      selectedDate: '#7b2d8e',
      hoverDate: '#5a2068',
    },
    libraryOverrides: {},
  },
  epfl: {
    id: 'epfl',
    name: 'École Polytechnique Fédérale de Lausanne',
    shortName: 'EPFL',
    searchQuery: 'EPFL',
    emailDomain: 'epfl.ch',
    country: 'CH',
    city: 'Lausanne',
    colors: {
      primary: '#003366',
      gradient: 'linear-gradient(135deg, #003366 0%, #005599 100%)',
      chipBg: '#003366',
      chipText: '#ffffff',
      selectedDate: '#003366',
      hoverDate: '#002244',
    },
    libraryOverrides: {},
  },
  unifr: {
    id: 'unifr',
    name: 'Université de Fribourg',
    shortName: 'UNIFR',
    searchQuery: 'UNIFR',
    emailDomain: 'unifr.ch',
    country: 'CH',
    city: 'Fribourg',
    colors: {
      primary: '#004d99',
      gradient: 'linear-gradient(135deg, #004d99 0%, #0066cc 100%)',
      chipBg: '#004d99',
      chipText: '#ffffff',
      selectedDate: '#004d99',
      hoverDate: '#003366',
    },
    libraryOverrides: {},
  },

  // ── France ───────────────────────────────────────────────
  unicaen: {
    id: 'unicaen',
    name: 'Université de Caen Normandie',
    shortName: 'UNICAEN',
    searchQuery: 'Caen',
    emailDomain: 'unicaen.fr',
    country: 'FR',
    city: 'Caen',
    colors: {
      primary: '#8b0000',
      gradient: 'linear-gradient(135deg, #8b0000 0%, #b22222 100%)',
      chipBg: '#8b0000',
      chipText: '#ffffff',
      selectedDate: '#8b0000',
      hoverDate: '#5c0000',
    },
    libraryOverrides: {},
  },
  univbs: {
    id: 'univbs',
    name: 'Université Bretagne Sud',
    shortName: 'UBS',
    searchQuery: 'Bretagne Sud',
    emailDomain: 'univ-ubs.fr',
    country: 'FR',
    city: 'Vannes',
    colors: {
      primary: '#0055a4',
      gradient: 'linear-gradient(135deg, #0055a4 0%, #0077cc 100%)',
      chipBg: '#0055a4',
      chipText: '#ffffff',
      selectedDate: '#0055a4',
      hoverDate: '#003d75',
    },
    libraryOverrides: {},
  },
  univangers: {
    id: 'univangers',
    name: 'Université Catholique de l\'Ouest',
    shortName: 'UCO',
    searchQuery: 'Angers',
    emailDomain: 'uco.fr',
    country: 'FR',
    city: 'Angers',
    colors: {
      primary: '#b22234',
      gradient: 'linear-gradient(135deg, #b22234 0%, #d4354a 100%)',
      chipBg: '#b22234',
      chipText: '#ffffff',
      selectedDate: '#b22234',
      hoverDate: '#8a1a28',
    },
    libraryOverrides: {},
  },
  uppa: {
    id: 'uppa',
    name: 'Université de Perpignan',
    shortName: 'UPVD',
    searchQuery: 'Perpignan',
    emailDomain: 'univ-perp.fr',
    country: 'FR',
    city: 'Perpignan',
    colors: {
      primary: '#c8102e',
      gradient: 'linear-gradient(135deg, #c8102e 0%, #e03050 100%)',
      chipBg: '#c8102e',
      chipText: '#ffffff',
      selectedDate: '#c8102e',
      hoverDate: '#9a0c22',
    },
    libraryOverrides: {},
  },
  uge: {
    id: 'uge',
    name: 'Université Gustave Eiffel',
    shortName: 'UGE',
    searchQuery: 'Gustave Eiffel',
    emailDomain: 'univ-eiffel.fr',
    country: 'FR',
    city: 'Champs-sur-Marne',
    colors: {
      primary: '#6b2c91',
      gradient: 'linear-gradient(135deg, #6b2c91 0%, #8b4cb8 100%)',
      chipBg: '#6b2c91',
      chipText: '#ffffff',
      selectedDate: '#6b2c91',
      hoverDate: '#4e1f6a',
    },
    libraryOverrides: {},
  },
  unimes: {
    id: 'unimes',
    name: 'Université de Nîmes',
    shortName: 'UNîMES',
    searchQuery: 'Nîmes',
    emailDomain: 'unimes.fr',
    country: 'FR',
    city: 'Nîmes',
    colors: {
      primary: '#d4354a',
      gradient: 'linear-gradient(135deg, #d4354a 0%, #e85570 100%)',
      chipBg: '#d4354a',
      chipText: '#ffffff',
      selectedDate: '#d4354a',
      hoverDate: '#a82838',
    },
    libraryOverrides: {},
  },
  unimes2: {
    id: 'unimes2',
    name: 'Université Marie et Louis Pasteur',
    shortName: 'UMLP',
    searchQuery: 'Marie Louis Pasteur',
    emailDomain: 'univ-fcomte.fr',
    country: 'FR',
    city: 'Besançon',
    colors: {
      primary: '#2e5090',
      gradient: 'linear-gradient(135deg, #2e5090 0%, #4070b0 100%)',
      chipBg: '#2e5090',
      chipText: '#ffffff',
      selectedDate: '#2e5090',
      hoverDate: '#1e3860',
    },
    libraryOverrides: {},
  },
  univEvry: {
    id: 'univEvry',
    name: 'Université d\'Évry',
    shortName: 'UEVE',
    searchQuery: 'Évry',
    emailDomain: 'univ-evry.fr',
    country: 'FR',
    city: 'Évry',
    colors: {
      primary: '#0055a4',
      gradient: 'linear-gradient(135deg, #0055a4 0%, #0077cc 100%)',
      chipBg: '#0055a4',
      chipText: '#ffffff',
      selectedDate: '#0055a4',
      hoverDate: '#003d75',
    },
    libraryOverrides: {},
  },

  // ── Italy ────────────────────────────────────────────────
  unipd: {
    id: 'unipd',
    name: 'Università degli Studi di Padova',
    shortName: 'UniPD',
    searchQuery: 'Padova',
    emailDomain: 'unipd.it',
    country: 'IT',
    city: 'Padova',
    colors: {
      primary: '#991b1b',
      gradient: 'linear-gradient(135deg, #991b1b 0%, #b91c1c 100%)',
      chipBg: '#991b1b',
      chipText: '#ffffff',
      selectedDate: '#991b1b',
      hoverDate: '#7f1d1d',
    },
    libraryOverrides: {},
  },
  unibo: {
    id: 'unibo',
    name: 'Università di Bologna',
    shortName: 'UniBo',
    searchQuery: 'Bologna',
    emailDomain: 'unibo.it',
    country: 'IT',
    city: 'Bologna',
    colors: {
      primary: '#006633',
      gradient: 'linear-gradient(135deg, #006633 0%, #008844 100%)',
      chipBg: '#006633',
      chipText: '#ffffff',
      selectedDate: '#006633',
      hoverDate: '#004d26',
    },
    libraryOverrides: {},
  },
  unicatt: {
    id: 'unicatt',
    name: 'Università Cattolica del Sacro Cuore',
    shortName: 'UCSC',
    searchQuery: 'Cattolica',
    emailDomain: 'unicatt.it',
    country: 'IT',
    city: 'Milano',
    colors: {
      primary: '#8b0000',
      gradient: 'linear-gradient(135deg, #8b0000 0%, #b22222 100%)',
      chipBg: '#8b0000',
      chipText: '#ffffff',
      selectedDate: '#8b0000',
      hoverDate: '#5c0000',
    },
    libraryOverrides: {},
  },
  unimib: {
    id: 'unimib',
    name: 'Università degli Studi di Milano-Bicocca',
    shortName: 'UniMiB',
    searchQuery: 'Bicocca',
    emailDomain: 'unimib.it',
    country: 'IT',
    city: 'Milano',
    colors: {
      primary: '#003366',
      gradient: 'linear-gradient(135deg, #003366 0%, #004d99 100%)',
      chipBg: '#003366',
      chipText: '#ffffff',
      selectedDate: '#003366',
      hoverDate: '#002244',
    },
    libraryOverrides: {},
  },
  unipv: {
    id: 'unipv',
    name: 'Università degli Studi di Pavia',
    shortName: 'UniPV',
    searchQuery: 'Pavia',
    emailDomain: 'unipv.it',
    country: 'IT',
    city: 'Pavia',
    colors: {
      primary: '#7b2d8e',
      gradient: 'linear-gradient(135deg, #7b2d8e 0%, #9b4db0 100%)',
      chipBg: '#7b2d8e',
      chipText: '#ffffff',
      selectedDate: '#7b2d8e',
      hoverDate: '#5a2068',
    },
    libraryOverrides: {},
  },
  unipolimi: {
    id: 'unipolimi',
    name: 'Politecnico di Milano',
    shortName: 'PoliMi',
    searchQuery: 'Politecnico Milano',
    emailDomain: 'polimi.it',
    country: 'IT',
    city: 'Milano',
    colors: {
      primary: '#003366',
      gradient: 'linear-gradient(135deg, #003366 0%, #005599 100%)',
      chipBg: '#003366',
      chipText: '#ffffff',
      selectedDate: '#003366',
      hoverDate: '#002244',
    },
    libraryOverrides: {},
  },
  unipoli: {
    id: 'unipoli',
    name: 'Politecnico di Torino',
    shortName: 'PoliTo',
    searchQuery: 'Politecnico Torino',
    emailDomain: 'polito.it',
    country: 'IT',
    city: 'Torino',
    colors: {
      primary: '#1a3c6e',
      gradient: 'linear-gradient(135deg, #1a3c6e 0%, #2a5ca8 100%)',
      chipBg: '#1a3c6e',
      chipText: '#ffffff',
      selectedDate: '#1a3c6e',
      hoverDate: '#122a4d',
    },
    libraryOverrides: {},
  },
  unimc: {
    id: 'unimc',
    name: 'Università di Macerata',
    shortName: 'UNIMC',
    searchQuery: 'Macerata',
    emailDomain: 'unimc.it',
    country: 'IT',
    city: 'Macerata',
    colors: {
      primary: '#8b0000',
      gradient: 'linear-gradient(135deg, #8b0000 0%, #b22222 100%)',
      chipBg: '#8b0000',
      chipText: '#ffffff',
      selectedDate: '#8b0000',
      hoverDate: '#5c0000',
    },
    libraryOverrides: {},
  },
  unina: {
    id: 'unina',
    name: 'Università degli Studi di Napoli Federico II',
    shortName: 'UniNa',
    searchQuery: 'Napoli',
    emailDomain: 'unina.it',
    country: 'IT',
    city: 'Napoli',
    colors: {
      primary: '#003366',
      gradient: 'linear-gradient(135deg, #003366 0%, #004d99 100%)',
      chipBg: '#003366',
      chipText: '#ffffff',
      selectedDate: '#003366',
      hoverDate: '#002244',
    },
    libraryOverrides: {},
  },

  // ── Luxembourg ───────────────────────────────────────────
  uniLux: {
    id: 'uniLux',
    name: 'University of Luxembourg',
    shortName: 'Uni.lu',
    searchQuery: 'Luxembourg',
    emailDomain: 'uni.lu',
    country: 'LU',
    city: 'Esch-sur-Alzette',
    colors: {
      primary: '#003366',
      gradient: 'linear-gradient(135deg, #003366 0%, #005599 100%)',
      chipBg: '#003366',
      chipText: '#ffffff',
      selectedDate: '#003366',
      hoverDate: '#002244',
    },
    libraryOverrides: {},
  },

  // ── Germany ──────────────────────────────────────────────
  uniWuppertal: {
    id: 'uniWuppertal',
    name: 'Bergische Universität Wuppertal',
    shortName: 'BUW',
    searchQuery: 'Wuppertal',
    emailDomain: 'uni-wuppertal.de',
    country: 'DE',
    city: 'Wuppertal',
    colors: {
      primary: '#003366',
      gradient: 'linear-gradient(135deg, #003366 0%, #004d99 100%)',
      chipBg: '#003366',
      chipText: '#ffffff',
      selectedDate: '#003366',
      hoverDate: '#002244',
    },
    libraryOverrides: {},
  },

  // ── Spain ────────────────────────────────────────────────
  uv: {
    id: 'uv',
    name: 'Universitat de València',
    shortName: 'UV',
    searchQuery: 'València',
    emailDomain: 'uv.es',
    country: 'ES',
    city: 'València',
    colors: {
      primary: '#003366',
      gradient: 'linear-gradient(135deg, #003366 0%, #004d99 100%)',
      chipBg: '#003366',
      chipText: '#ffffff',
      selectedDate: '#003366',
      hoverDate: '#002244',
    },
    libraryOverrides: {},
  },
};

export function getUniversity(id: string): University {
  return universities[id] || universities.ulb;
}

export function getAllUniversities(): University[] {
  return Object.values(universities);
}

export function getUniversitiesByCountry(): Record<string, University[]> {
  const grouped: Record<string, University[]> = {};
  for (const uni of Object.values(universities)) {
    const country = uni.country || 'Other';
    if (!grouped[country]) grouped[country] = [];
    grouped[country].push(uni);
  }
  return grouped;
}

export const DEFAULT_UNIVERSITY = 'ulb';

export default universities;
